### ISSUE TITLE
Getting my turtle to move

### ISSUE THREAD

**Issue by Graceblazevic** [Graceblazevic/book#1]
Hi,
I want my turtle to move (float) round and bounce off the walls of the screen by its self randomly. 
As i'm having trouble finding code off online

Thanks Grace

**Comment by Graceblazevic** [comment]
Aiming for plane that you have moving round in your childcare centre website if i could please have the code for it

**Comment by ellysmlly** [comment]
@Graceblazevic When this is resolved & your merge the PR make sure you also close this issue & log that its fixed 💯 

Very cool
