### ISSUE TITLE
dragging on Iphone

### ISSUE THREAD

**Issue by Graceblazevic** [Graceblazevic/book#6]
My dragging in not working on Iphone  when I go to click and drag the Crane, penguin and statue across the page its not working but it works fine on the web (laptop)

**Comment by sehsarah** [comment]
Are you using jquery UI? Then this works http://touchpunch.furf.com/

**Comment by sehsarah** [comment]
Replaced the custom JS drag methods (that were repeated 3 times) with the jquery UI drag library and method above of mobile support
